#!/bin/bash

################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) \
  --env-type 'BINANCE_SPOT_ETH-USDT,2021-11-30 00:00:00,2021-12-31 00:00:00,1440' --env-name "prices-v0" --env-num 500 --roll-num 1 --max-stepsM 1.02 \
  --env-mode supervise --minmax-score="0,10000" \
  --agt-mode singlefull --stack-num 1 --memo-size 1 \
  --alg-mode XGbst --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc cnn2d --apfparas 3,3,1,1,0,0,64,0^3,3,1,1,0,0,128,0=576 \
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,128,0^3,3,2,2,1,1,256,0=576 \
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
done
exit 1
################################################################################
# marl6







################################################################################
for ((i=$1; i<$1+$2; i++))
do
#   kernprof -l \
#   main.py --env-seed $i --fin-seed $(($1+$2-1)) \
#   --env-type 'cinic' --env-name "vision-v0" --env-num 500 --roll-num 1 --max-stepsM 1.2 \
#   --env-mode supervise --minmax-score="0,10000" \
#   --agt-mode singlefull --stack-num 1 --memo-size 1 \
#   --alg-mode PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
#   --aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,128,0^3,3,2,2,1,1,256,0=576 \
#   #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
# done
# exit 1
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) \
  --env-type 'BINANCE_SPOT_ETH-USDT,10.12.2021,30.12.2021,1' --env-name "prices-v0" --env-num 500 --roll-num 1 --max-stepsM 1.2 \
  --env-mode supervise --minmax-score="0,10000" \
  --agt-mode singlefull --stack-num 1 --memo-size 1 \
  --alg-mode XGbst --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc cnn2d --apfparas 3,3,1,1,0,0,64,0^3,3,1,1,0,0,128,0=576 \
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,128,0^3,3,2,2,1,1,256,0=576 \
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
done
exit 1
# ################################################################################
# for ((i=$1; i<$1+$2; i++))
# do
#   #python cv.py $i 'mnist' 'lenet' 100 0.1 0.9 0.5 20 200
#   python cv.py $i 'cinic' 'vgg16' 100 0.1 0.9 0.5 20 200
#   #python cv.py $i 'cinic' 'vgg19' 100 0.1 0.9 0.5 20 200
#   #python cv.py $i 'cinic' 'res18' 100 0.1 0.9 0.5 20 200
# done
# exit 1
# #  python nlp.py $i 'sst' 'rnn' 100 0.1 0.9 0.5 20 20
# ################################################################################
# for ((i=$1; i<$1+$2; i++))
# do
#   kernprof -l \
#   main.py --env-seed $i --fin-seed $(($1+$2-1)) \
#   --env-type 'mnist' --env-name "vision-v0" --env-num 500 --roll-num 1 --max-stepsM 1.2 \
#   --env-mode supervise --minmax-score="9000,10000" \
#   --agt-mode singlefull --stack-num 1 --memo-size 1 \
#   --alg-mode PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
#   --aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
#   #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
# done
# exit 1
# # mnist 2min10sec 20 epoch train almost 100% test 99.0%
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) \
  --env-type 'cinic' --env-name "vision-v0" --env-num 500 --roll-num 1 --max-stepsM 18.2 \
  --env-mode supervise --minmax-score="0,10000" \
  --agt-mode singlefull --stack-num 1 --memo-size 1 \
  --alg-mode PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc res18 --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug

  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) \
  --env-type 'cinic' --env-name "vision-v0" --env-num 500 --roll-num 1 --max-stepsM 18.2 \
  --env-mode supervise --minmax-score="0,10000" \
  --agt-mode singlefull --stack-num 1 --memo-size 1 \
  --alg-mode PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc vgg19 --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug

  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) \
  --env-type 'cinic' --env-name "vision-v0" --env-num 500 --roll-num 1 --max-stepsM 18.2 \
  --env-mode supervise --minmax-score="0,10000" \
  --agt-mode singlefull --stack-num 1 --memo-size 1 \
  --alg-mode PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,20,0.5 --opt Adam --opt-alpha 0.09 --opt-eps 5e-4 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc vgg16 --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
done
exit 1
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) --teamagts 2 \
  --env-type 'mpe' --env-name "simple_spread_v2" --env-num 32 --roll-num 5 --max-stepsM 0.5 \
  --env-mode multifull --minmax-score="-100,0" \
  --agt-mode multifull --stack-num 2 --memo-size 5 \
  --alg-mode PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn3d --apfparas 12,1,2,2,2,1,0,0,0,64,1=64 \
  #--test-steps 150 --render --fps 20 #--drawinfo 1,1,0,0
done
exit 1
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) --teamagts 2,2 \
  --env-type 'magent' --env-name "battle_v3" --env-num 32 --roll-num 5 --max-stepsM 5 \
  --env-mode multifull --minmax-score="-50,50" \
  --agt-mode multifull --stack-num 3 --memo-size 5 \
  --alg-mode PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn3d --apfparas 5,5,2,2,2,1,0,0,0,64,1^4,4,1,1,1,1,0,0,0,64,1=512 \
  #--test-steps 500 --render --fps 120 #--drawinfo 1,1,0,0
  #--aprxfunc cnn3d --apfparas 4,4,3,1,1,1,0,0,0,32,1^4,4,2,2,2,1,0,0,0,64,1^3,3,1,1,1,1,0,0,0,64,1=512 \
done
exit 1
################################################################################
# from zoo.mpe import simple_v2, simple_adversary_v2, simple_crypto_v2, simple_push_v2, simple_reference_v2, simple_speaker_listener_v3
# from zoo.mpe import simple_spread_v2, simple_tag_v2, simple_world_comm_v2
# from zoo.magent import battle_v3,battlefield_v3,combined_arms_v5,adversarial_pursuit_v3,tiger_deer_v3,gather_v3
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) \
  --env-type 'atari' --env-name "BreakoutNoFrameskip-v4" --env-num 64 --roll-num 5 --max-stepsM 10 \
  --env-mode singlefull --minmax-score="0,500" \
  --agt-mode singlefull --stack-num 4 --memo-size 5 \
  --alg-mode PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn3d --apfparas 8,8,3,4,4,1,0,0,0,32,1^4,4,2,2,2,1,0,0,0,64,1^3,3,1,1,1,1,0,0,0,64,1=512 \
  #--test-steps 5000 --render --fps 120 #--drawinfo 1,1,0,0
  #--aprxfunc cnn2d --apfparas 8,8,4,4,0,0,32,0^4,4,2,2,0,0,64,0^3,3,1,1,0,0,64,0=512 \
done
exit 1
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l \
  main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-type 'atari' --env-name "BreakoutNoFrameskip-v0" --env-num 64 --roll-num 5 --max-stepsM 10 \
  --env-mode full --minmax-score="0,500" \
  --agt-mode imagine --stack-num 4 --memo-size 5 \
  --alg-mode PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,32,0^4,4,2,2,0,0,64,0^3,3,1,1,0,0,64,0=512 \
  #--test-steps 5000 --render --fps 120 #--drawinfo 1,1,0,0
  #--aprxfunc cnn3d --apfparas 8,8,3,4,4,1,0,0,0,32,1^4,4,2,2,2,1,0,0,0,64,1^3,3,1,1,1,1,0,0,0,64,1=512 \
  #--aprxfunc cnn2d --apfparas 8,8,4,4,0,0,32,0^4,4,2,2,0,0,64,0^3,3,1,1,0,0,64,0=512 \
  #--aprxfunc res2d --apfparas 8,4,0,32,1^3,2,0,0,1^32,1,1,1,1=512 \
done
exit 1
# 10M step cnn3d 64 1h27m cnn2d 64 1h3.5m res2d 1h30m
#--play-num 4 --type-num 2 --unit-num 5 --envparas 10,1000_ --agtparas 3,3,5,8,1,3,1 --npcparas 4,4,5,32,1,1,1 --switches 0,0,0 \
################################################################################









################################################################################
for ((i=$1; i<$1+$2; i++))
do
  kernprof -l main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "BeamRiderNoFrameskip-v4" --minmax-score="0,5000" --envir part --pobparas 1.0 --max-stepsM 10 \
  --stack-num 4 --agent imagine --memoplace agtcpu \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc rnn2dtest --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--to-test --testlength 0.15 --render --fps 30
done
exit 1
  kernprof -l main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "AsteroidsNoFrameskip-v4" --minmax-score="0,5000" --envir part --max-stepsM 10 \
  --stack-num 4 --agent imagine --memoplace agtcpu \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc rnn2dtest --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--to-test --testlength 0.15 --render --fps 30

  kernprof -l main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "CentipedeNoFrameskip-v4" --minmax-score="0,5000" --envir part --max-stepsM 10 \
  --stack-num 4 --agent imagine --memoplace agtcpu \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc rnn2dtest --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--to-test --testlength 0.15 --render --fps 30

  kernprof -l main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "ChopperCommandNoFrameskip-v4" --minmax-score="0,5000" --envir part --max-stepsM 10 \
  --stack-num 4 --agent imagine --memoplace agtcpu \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc rnn2dtest --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--to-test --testlength 0.15 --render --fps 30

  kernprof -l main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "MsPacmanNoFrameskip-v4" --minmax-score="0,5000" --envir part --max-stepsM 10 \
  --stack-num 4 --agent imagine --memoplace agtcpu \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc rnn2dtest --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--to-test --testlength 0.15 --render --fps 30
done
exit 1
#--apfparas 8,8,4,4,0,0,64,0^4,4,2,2,0,0,64,0^3,3,1,1,0,0,64,0=512 \
#--apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 100 --roll-num 1 --memo-size 1 \
  --env-name "mnist-v0" --minmax-score="0,10000" --envir supervise --max-stepsM 1.2 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_1_1_1" --stack-num 1 --agent imagine --memoplace agtcpu --savenum 2 --agtonoff 0 \
  --algo PTa2c1 --lr-M 10000 --decay step --decayparas 0.01,2500,0.5 --opt SGD --alpha 0.9 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc cnn2dtest --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--aprxfunc cnn2d --apfparas 3,3,1,1,1,1,48,0^3,3,2,2,1,1,96,0^3,3,1,1,1,1,192,0^3,3,2,2,1,1,256,0=512^64 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
done
#python graph.py ""
exit 1
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --env-name "moveMM-v0" --minmax-score="0,100" --envir full --max-stepsM 1 \
  --play-num 4 --type-num 1 --unit-num 10 --envparas 11,11,3,1_10,500_0,1,0,-60,0,60 --envonoff 0,0,2 \
  --npcparas 0,0,5,32,1,3,1 --agtparas 1,1,5,8,1,3,1 \
  --learnflag="0_-1_-1_-1" --stack-num 1 --agent imagineMold --memoplace agtcpu --savenum 2 --agtonoff 0 \
  --algo PTa2c1M --lr-M 1500 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 3,3,1,1,1,1,32,1^3,3,2,2,1,1,256,1=128 \
  --to-test --testlength 0.5 --render --fps 12 --zoom-in 128 #--debug
done
exit 1
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 500 --roll-num 1 --memo-size 1 \
  --env-name "mnist-v0" --minmax-score="9000,10000" --envir supervise --max-stepsM 1.4 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_1_1_1" --stack-num 1 --agent imagine --memoplace agtcpu --savenum 2 --agtonoff 0 \
  --algo PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,, --opt Adam --alpha 0.0 --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 5 --render --fps 60 #--zoom-in 32 #--debug
done
#python graph.py ""
# mnist 2min10sec 20 epoch train almost 100% test 99.0%
exit 1
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 512 --roll-num 1 --memo-size 1 \
  --env-name "mnist-v0" --minmax-score="0,1" --envir supervise --max-stepsM 0.12 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_1_1_1" --stack-num 1 --agent imagine --memoplace agtcpu --savenum 2 --agtonoff 0 \
  --algo PTa2c1 --lr-M 20000 --decay linear --decayparas 0.01,, --opt Adam --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 \
  #--to-test --testlength 0.15 --render --fps 60 #--zoom-in 32 #--debug
done
python graph.py ""
exit 1
# 11 seconds
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 16 --roll-num 1 --memo-size 1 \
  --env-name "mnist-v0" --minmax-score="0,1" --envir supervise --max-stepsM 0.0002 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 1 --agent CCA --memoplace agtcpu --savenum 2 --agtonoff 0 \
  --algo PTa2c1 --lr-M 2000000 --decay const --decayparas 0.01,, --opt SGD --vlossratio 0.0 --entropycoef 0.0 \
  --aprxfunc cnn2dtest --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 --drawinfo 1,1,1,1 \
  #--to-test --testlength 0.15 --render --fps 60 #--zoom-in 32 #--debug
done
python graph.py ""
exit 1
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 --drawinfo 0,0,0,0 \ 9sec --max-stepsM 0.01
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 --drawinfo 0,0,0,0 \ 8sec --max-stepsM 0.01
  #--aprxfunc cnn2d --apfparas 6,6,2,2,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=144 --drawinfo 1,1,0,0 \ 8min --max-stepsM 0.002 1,1,1,1 \ 160min 1,1,1,0 \ 100min
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 12 --roll-num 5 --memo-size 5 \
  --env-name "CCA-v0" --minmax-score="0,100" --envir full --max-stepsM 0.01 \
  --envparas 4,110,1,10 --stack-num 1 --agent CCA \
  --algo PTa2c1 --lr-M 2010 \
  --aprxfunc cnn2d --apfparas 3,1,1,1,1,0,4,0^3,1,1,1,1,0,8,0=16 \
  #--to-test --testlength 0.5 --render --fps 12 #--zoom-in 32 #--debug
done
exit 1
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "BeamRiderNoFrameskip-v4" --minmax-score="0,7500" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent CCA --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  --to-test --testlength 0.15 --render --fps 60 #--drawinfo 0,0,0,0 #--zoom-in 32 #--debug
done
exit 1
  #--aprxfunc cnn2d --apfparas 5,5,3,3,2,2,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=256 \
  #--aprxfunc cnn2d --apfparas 5,5,3,3,2,2,512,0^3,3,2,2,1,1,1024,0^3,3,2,2,1,1,2048,0=2048 \
  #--aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--aprxfunc cnn2d --apfparas 15,15,3,3,0,0,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--aprxfunc cnn2d --apfparas 9,9,4,4,8,9,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0^3,3,2,2,1,1,64,0=576 \
  #--aprxfunc cnn2d --apfparas 15,15,3,3,0,0,64,0^9,9,3,3,0,0,64,0^3,3,2,2,1,1,64,0=576 \
  #--drawinfo 0,0,0,0 --testlength 1.5 5min #--drawinfo 1,1,0,0 --testlength 0.15 120min
################################################################################
# 55556 for 10M and 50M steps 
# 27778 for  5M and 25M steps 
# 16666 for  3M and 15M steps RMSprop Acktr Adam
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "BreakoutNoFrameskip-v4" --minmax-score="0,600" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--to-test --testlength 1.5 --render --fps 120 #--zoom-in 32 #--debug
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "EnduroNoFrameskip-v4" --minmax-score="0,750" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--to-test --testlength 1.5 --render --fps 120 #--zoom-in 32 #--debug
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "SpaceInvadersNoFrameskip-v4" --minmax-score="0,1500" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--to-test --testlength 1.5 --render --fps 120 #--zoom-in 32 #--debug
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "QbertNoFrameskip-v4" --minmax-score="0,15000" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--to-test --testlength 1.5 --render --fps 120 #--zoom-in 32 #--debug
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "SeaquestNoFrameskip-v4" --minmax-score="0,3000" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--to-test --testlength 1.5 --render --fps 120 #--zoom-in 32 #--debug
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 \
  --gameflag 'atari' --env-name "BeamRiderNoFrameskip-v4" --minmax-score="0,7500" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 1 --unit-num 40 --envparas 21,400,5000_0.01,-10,0.5 --envonoff 1,1 \
  --learnflag="1_0_1_1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --agtonoff 0 \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 8,8,4,4,0,0,64,1^4,4,2,2,0,0,64,1^3,3,1,1,0,0,64,1=512 \
  #--to-test --testlength 1.5 --render --fps 120 #--zoom-in 32 #--debug
done
exit 1
#BreakoutNoFrameskip Enduro SpaceInvaders Qbert Seaquest  Pong  BeamRider
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 64 --roll-num 5 --memo-size 5 --gameflag 'atari' --env-name "BreakoutNoFrameskip-v4" --minmax-score="0,500" --envir full --max-stepsM 10 \
  --play-num 4 --type-num 2 --unit-num 5 --envparas 10,1000_ --agtparas 3,3,5,8,1,3,1 --npcparas 4,4,5,32,1,1,1 --switches 0,0,0 \
  --learnflag="0,0_-1,-1_-1,-1_-1,-1" --stack-num 4 --agent imagine --memoplace agtcpu --savenum 5 --timer \
  --algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop --aprxfunc cnn2d --apfparas 8,8,4,4,32,1^4,4,2,2,64,1^3,3,1,1,64,1^7,7=512 \
  #--algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop --aprxfunc res2d --apfparas 8,4,0,32,1^3,2,0,0,1^32,1,1,1,1=512 \
  #--algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop --aprxfunc cnn2d --apfparas 8,8,4,4,32,1^4,4,2,2,64,1^3,3,1,1,64,1^7,7=512 \
  #--algo PTa2c1 --lr-M 700 --decay linear --decayparas 0.01,, --opt RMSprop --aprxfunc cnn3d --apfparas 8,8,3,4,4,1,0,0,0,32,1^4,4,2,2,2,1,0,0,0,64,1^3,3,1,1,1,1,0,0,0,64,1=512 \
  #--to-test --testlength 0.015 --render --fps 12 #--zoom-in 32 #--debug
done
exit 1
# 10M step cnn3d 64 1h27m cnn2d 64 1h3.5m res2d 1h30m
################################################################################
for filename in *.mp4
do
    ffmpeg -i $filename ${filename%.mp4}'_s.mp4'
    rm $filename
done
#-vcodec libx265 -crf 24
################################################################################
for ((i=$1; i<$1+$2; i++))
do
  python main.py --env-seed $i --fin-seed $(($1+$2-1)) --env-num 8 --roll-num 5 --memo-size 5 \
  --env-name "haliteM-v0" --minmax-score="-400,100" --envir full --max-stepsM 2 \
  --play-num 4 --type-num 1 --unit-num 10 --envparas 11,200,2000_0.01,-10,0.5 --envonoff 1,0 \
  --learnflag="0_-1_-1_-1" --stack-num 1 --agent haliteM --memoplace agtcpu --savenum 2 --agtonoff 0 \
  --algo PTa2c1M --lr-M 1500 --decay linear --decayparas 0.01,, --opt RMSprop \
  --aprxfunc cnn2d --apfparas 3,3,1,1,1,1,32,1^3,3,2,2,1,1,256,1=128 \
  #--to-test --testlength 0.015 --render --fps 12 #--zoom-in 32 #--debug
done
exit 1
# 15h
# no act no update 2h
# no act no update no stack obs for multiplayer multitype 1h
# no act no update no stack obs for multiplayer multitype 0.21M 0.59min
#  4 act no update    stack obs for multiplayer multitype 0.21M 4.47min
#  1 act no update    stack obs for multiplayer multitype 0.21M 1.09min
#  1 act  1 update    stack obs for multiplayer multitype 0.21M 3.71min
#  1 act  1 update    stack obs for multiplayer multitype   10M 3h30min
#layer s : [84, 84, 4, 1]
#layer 0 : [20, 20, 2] 32
#layer 1 : [9, 9, 1] 64
#layer 2 : [7, 7, 1] 64
#layer l : 512
#1717413 6144 32 65536 64 36864 64 1605632 512 512 1 2048 4
